# Generated by Django 5.2.3 on 2025-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_auto_20210610_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre de estudiante'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=30),
        ),
    ]
